<?php

namespace ContainerATp2tPO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5i24bZDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5i24bZD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5i24bZD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'klantRepository' => ['privates', 'App\\Repository\\KlantRepository', 'getKlantRepositoryService', true],
        ], [
            'entityManager' => '?',
            'klantRepository' => 'App\\Repository\\KlantRepository',
        ]);
    }
}
