<?php

namespace ContainerATp2tPO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BebChzDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bebChzD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bebChzD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contractRepository' => ['privates', 'App\\Repository\\ContractRepository', 'getContractRepositoryService', true],
        ], [
            'contractRepository' => 'App\\Repository\\ContractRepository',
        ]);
    }
}
