<?php

namespace ContainerATp2tPO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Autocomplete_EntityTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.autocomplete.entity_type' shared service.
     *
     * @return \Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType
     *
     * @deprecated Since symfony/ux-autocomplete 2.13: The "ux.autocomplete.entity_type" form type is deprecated since 2.13. Use "ux.autocomplete.base_entity_type" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/ux-autocomplete', '2.13', 'The "ux.autocomplete.entity_type" form type is deprecated since 2.13. Use "ux.autocomplete.base_entity_type" instead.');

        return $container->privates['ux.autocomplete.entity_type'] = new \Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType(($container->services['router'] ?? self::getRouterService($container)));
    }
}
