<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Klant extends \App\Entity\Klant implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contract' => [parent::class, 'contract', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'naam' => [parent::class, 'naam', null],
        "\0".parent::class."\0".'telefoonnummer' => [parent::class, 'telefoonnummer', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'contract' => [parent::class, 'contract', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'naam' => [parent::class, 'naam', null],
        'telefoonnummer' => [parent::class, 'telefoonnummer', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
