<?php

namespace ContainerHzBilPx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yhfa0p9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yhfa0p9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yhfa0p9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nearestLocationRepository' => ['privates', 'App\\Repository\\NearstLocationRepository', 'getNearstLocationRepositoryService', true],
        ], [
            'nearestLocationRepository' => 'App\\Repository\\NearstLocationRepository',
        ]);
    }
}
