# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

index:
    path: /
    controller: App\Controller\MainController::index

Main:
    path: /main
    controller: App\Controller\MainController::index

Login:
    path: /login
    controller: App\Controller\LoginController::login

Register:
    path: /register
    controller: App\Controller\RegistrationController::register
