# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

index:
    path: /
    controller: App\Controller\SecurityController::login

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Security\SecurityController::logout

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_data_acq:
    path: /data_acq
    controller: App\Controller\DataAcqController::index

app_dev_maintan:
    path: /dev_maintan
    controller: App\Controller\DevMaintanController::index

app_service_manage:
    path: /service_manage
    controller: App\Controller\ServiceManageController::index
# config/routes.yaml
# config/routes.yaml

post_weather_data:
    path: /postWeatherData
    controller: App\Controller\WeatherDataController::postWeatherData
    methods: [POST]

get_weather_data:
    path: /weatherData
    controller: App\Controller\DevMaintanController::weatherData
    methods: [GET]
