# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

index:
    path: /
    controller: App\Controller\SecurityController::login

admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Security\SecurityController::logout

register:
    path: /register
    controller: App\Controller\RegistrationController::register

data_acq:
    path: /data_acq
    controller: App\Controller\DataAcqController::index
