<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATp2tPO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATp2tPO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATp2tPO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATp2tPO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerATp2tPO\App_KernelDevDebugContainer([
    'container.build_hash' => 'ATp2tPO',
    'container.build_id' => 'b9228ca6',
    'container.build_time' => 1713460434,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATp2tPO');
