<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrtvZPX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrtvZPX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrtvZPX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrtvZPX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLrtvZPX\App_KernelDevDebugContainer([
    'container.build_hash' => 'LrtvZPX',
    'container.build_id' => 'cf035235',
    'container.build_time' => 1713471543,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrtvZPX');
